### ISSUE TITLE
`db.mw` Roadmap

### ISSUE THREAD

**Issue by nathanclevenger** [drivly/db.mw#1]
```[tasklist]
### Roadmap
- [ ] https://github.com/drivly/db.mw/issues/2
- [ ] https://github.com/drivly/db.mw/issues/3
- [ ] https://github.com/drivly/db.mw/issues/4
- [ ] https://github.com/drivly/db.mw/issues/6
```
